### ISSUE TITLE
deepkit link error

### ISSUE THREAD

**Issue by VinuAbraham** [deepkit/deepkit#16]
I have installed deepkit using snap in ubuntu and created folder as shown in the website(getting started), but when I am trying "deepkit link" an error is showing like 

Error: No account found for localhost.
    at Je.getLocalAccount (/snap/deepkit/12/resources/app/deepkit-cli/main.js:441:216380)
    at /snap/deepkit/12/resources/app/deepkit-cli/main.js:441:345337
    at async Ai.run (/snap/deepkit/12/resources/app/deepkit-cli/main.js:441:345279)
    at async Ai._run (/snap/deepkit/12/resources/app/deepkit-cli/main.js:174:138701)
    at async h.runCommand (/snap/deepkit/12/resources/app/deepkit-cli/main.js:174:89044)
    at async i.run (/snap/deepkit/12/resources/app/deepkit-cli/main.js:174:210359)
    at async i._run (/snap/deepkit/12/resources/app/deepkit-cli/main.js:174:138701)

**Comment by marcj** [comment]
@VinuAbraham Thanks for the report. Did you start the app first? Try `deepkit --app` first.

**Comment by VinuAbraham** [comment]
it worked thanks...There was no reference of the command deepkit --app in the website... Anyway thanks again..
