### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by rorph** [deepkit/deepkit#17]
Hello,

I'm trying to build the docker locally, but it fails on `leana`:

```
Step 14/29 : RUN cd /app && npm run bootstrap
 ---> Running in acaa693b066c

> root@ bootstrap /app
> lerna bootstrap --nohoist \* --no-ci

lerna notice cli v3.22.1
lerna info Bootstrapping 4 packages
lerna info Installing external dependencies
lerna ERR! npm install exited 1 in '@deepkit/server'
lerna ERR! npm install stdout:

> bson-ext@2.0.3 install /app/packages/server/node_modules/bson-ext
> (node-gyp rebuild 2> builderror.log) || (exit 0)


> nodegit@0.26.4 install /app/packages/server/node_modules/nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] Running install script
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/app/packages/server/node_modules/nodegit/build/Release/nodegit.node --module_name=nodegit --module_path=/app/packages/server/node_modules/nodegit/build/Release --napi_ver
sion=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v67' (1)

lerna ERR! npm install stderr:
node-pre-gyp
WARN Using request for node-pre-gyp https download
node-pre-gyp
WARN Tried to download(404): https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.26.4-node-v67-linux-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for nodegit@0.26.4 and node@11.15.0 (node-v67 ABI, musl) (falling back to source compile with node-gyp)

/bin/sh: krb5-config: not found
gyp: Call to 'krb5-config gssapi --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp

ERR! configure error

gyp
ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack
at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR!
stack     at ChildProcess.emit (events.js:193:13)
gyp ERR!
stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:255:12)
gyp
ERR! System Linux 4.15.0-99-generic
gyp
ERR! command
"/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/app/packages/server/node_modules/nodegit/build/Release/nodegit.node" "--module_name=nodegit" "--module_path=/app/packages/server/node_modules/nodegit/build/Release" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v67"
gyp ERR! cwd
/app/packages/server/node_modules/nodegit
gyp ERR!
node -v v11.15.0
gyp
ERR! node-gyp -v v3.8.0
....
```

Apparently this:
`WARN Tried to download(404): https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.26.4-node-v67-linux-x64.tar.gz` 

is missing.

Any ideas?

Thanks!

**Comment by marcj** [comment]
Docker build is not used anymore. We use regular Makefiles. The Dockerfile at root will soon be removed.
